### ISSUE TITLE
Need to check artifact result of checkpoint swinir.pth

### ISSUE THREAD

**Issue by yh-yoon** [JNNNNYao/LINF#1]
Hello, I tried to visualize the result of swinir(temperature=0), however, there are some artifact results in Set5 images.

May I request a correction to the implementation code?

Other models (EDSR, RDN) have a correct results.

I used this command "python test.py --config ./configs/test/test-set5-4.yaml --model pth/swinir.pth --gpu 0 --sample 5 --temperature 0.0"

<img width="567" alt="image" src="https://github.com/JNNNNYao/LINF/assets/71309159/b6d333dd-1b04-4bb8-9a01-8cb3f02c417f">

**Comment by JNNNNYao** [comment]
Hi, it should work by adding argument --window 8 to the command. The --window argument controls the window size of Swin Transformer.

**Comment by yh-yoon** [comment]
Thanks for your help! I solved this problem by using "--window 8", but I also added "pred = pred[:,:,:-h_pad*scale,:-w_pad*scale]" in test.py due to the dimension error. Thank you.
